# project name
name: aoyagi-practice-docker-compose

# このファイル定義しているコンテナー
services:
  aoyagi-db:
    image: mysql:latest
    container_name: aoyagi-practice-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: "aoyagi_mysql_db"
    ports:
      - "1234:3306"
    volumes:
      - db_data:/var/lib/mysql

  aoyagi-php:
    build: 
      context: docker/php
    container_name: aoyagi-practice-php
    ports:
      - "5678:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - aoyagi-db

volumes:
  db_data:
